### PR TITLE
Feature/nsmutabledict category

### LINKED ISSUE #21: Clean up SDL Structs with a category on NSMutableDictionary
Every setter method in every SDLRPCStruct subclass takes an object and sets it in the store. If the object passed into the method is nil, the object is removed from the store instead (because passing nil to setObject throws an NSInvalidArgumentException).  This makes every setter look like

```ObjC
-(void) setNavigationText:(NSString*) navigationText {
    if (navigationText != nil) {
        [store setObject:navigationText forKey:NAMES_navigationText];
    } else {
        [store removeObjectForKey:NAMES_navigationText];
    }
}
```

This can be cleaned up by creating a category on NSMutableDictionary and including it in the SDLRPCStruct class.  It would look like

```ObjC
- (void)setOrRemoveObject:(id)object forKey:(id <NSCopying>)key {
    if (nil != object) {
        [self setObject:object forKey:key];
    } else {
        [self removeObjectForKey:key];
    }
}
```

Then every setter can be reduced to

```ObjC
- (void)setNavigationText:(NSString *)navigationText {
    [store setOrRemoveObject:navigationText forKey:NAMES_navigationText];
}
```

### PR DESCRIPTION
**Pull request by justinjdickow**
fixes #21

### CODE REVIEW

**Comment by joeljfischer** [comment]
Note that to be comprehensive, this category would have to be used ~370 more places

**Comment by justinjdickow** [comment]
@hugh22 @adein Can somebody please review this change so we can merge the pull request?

**Comment by mikeburke106** [comment]
This PR has been sitting in limbo for ~3 months and we've asked for updates multiple times with no response.  I propose that we discuss this PR in the next call and then allow 2 more weeks for a final review.  If all is good by the following call, I propose we mark this PR for approval and merge.

I understand that everyone is very busy, but please do what you can to put a priority on these pull requests, as they are the future of the project.  The more people we have reviewing them, the fewer mistakes will make it into the code.  Thanks everyone.

**Comment by mikeburke106** [comment]
I just reviewed the commit diffs and everything looks good to me.

**Comment by joeljfischer** [comment]
This needs to be into the `develop` branch

**Pull request closed without merging**
